apiVersion: configs.example.io/v1alpha1
kind: ConfigSync
metadata:
  labels:
    app.kubernetes.io/name: config-synchronizer-operator
    app.kubernetes.io/managed-by: kustomize
  name: configsync-sample
spec:
  source:
    git:
      path: "."
      repoURL: https://github.com/Joe-Bresee/Config-Synchronizer-Operator-test-git-source.git
      branch: main
      # authMethod: https
      # authSecretRef:
      #   namespace: default
      #   name: git-creds
  targets:
    - namespace: default
      name: test-deploy
      type: Deployment
  refreshInterval: "5s"